# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'untitled.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Mq(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"Mq")
        MainWindow.resize(640, 486)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(0, 0, 641, 461))
        self.label.setPixmap(QPixmap(u"desk_app/assets/material-design-wallpaper-10.png"))
        self.label.setScaledContents(True)
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(40, 110, 581, 341))
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.label_5 = QLabel(self.tab)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(180, 20, 231, 16))
        self.label_5.setStyleSheet(u"color: white;")
        self.label_7 = QLabel(self.tab)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(0, 0, 581, 61))
        self.label_7.setPixmap(QPixmap(u"desk_app/assets/material-design-wallpaper-2.png"))
        self.label_7.setScaledContents(False)
        self.label_3 = QLabel(self.tab)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(0, 60, 581, 51))
        self.label_3.setPixmap(QPixmap(u"desk_app/assets/material-design-wallpaper-10.png"))
        self.label_9 = QLabel(self.tab)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(80, 80, 461, 20))
        font = QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet(u"color: white;")
        self.ppm = QLabel(self.tab)
        self.ppm.setObjectName(u"ppm")
        self.ppm.setGeometry(QRect(260, 140, 71, 71))
        font1 = QFont()
        font1.setPointSize(20)
        self.ppm.setFont(font1)
        self.ppm.setStyleSheet(u"color: white;")
        self.ppm.setAlignment(Qt.AlignCenter)
        self.label_11 = QLabel(self.tab)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(120, 260, 201, 16))
        font2 = QFont()
        font2.setPointSize(15)
        self.label_11.setFont(font2)
        self.label_11.setStyleSheet(u"color: white;")
        self.resultado = QLabel(self.tab)
        self.resultado.setObjectName(u"resultado")
        self.resultado.setGeometry(QRect(330, 260, 75, 16))
        self.resultado.setStyleSheet(u"color: white;")
        self.label_13 = QLabel(self.tab)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(330, 170, 31, 16))
        self.label_13.setStyleSheet(u"color: white;")
        self.label_16 = QLabel(self.tab)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(0, 110, 581, 201))
        self.label_16.setPixmap(QPixmap(u"desk_app/assets/material-design-wallpaper-2.png"))
        self.label_16.setScaledContents(False)
        self.tabWidget.addTab(self.tab, "")
        self.label_16.raise_()
        self.label_7.raise_()
        self.label_5.raise_()
        self.label_3.raise_()
        self.label_9.raise_()
        self.ppm.raise_()
        self.label_11.raise_()
        self.resultado.raise_()
        self.label_13.raise_()
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.label_4 = QLabel(self.tab_2)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(0, -1, 581, 61))
        self.label_4.setPixmap(QPixmap(u"desk_app/assets/material-design-wallpaper-2.png"))
        self.label_4.setScaledContents(False)
        self.label_6 = QLabel(self.tab_2)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(190, 20, 181, 20))
        self.label_6.setStyleSheet(u"color:white;")
        self.label_8 = QLabel(self.tab_2)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(0, 60, 581, 51))
        self.label_8.setPixmap(QPixmap(u"desk_app/assets/material-design-wallpaper-10.png"))
        self.label_10 = QLabel(self.tab_2)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(70, 80, 481, 16))
        self.label_10.setFont(font)
        self.label_10.setStyleSheet(u"color: white;")
        self.label_12 = QLabel(self.tab_2)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(380, 120, 75, 16))
        self.label_12.setStyleSheet(u"color: white;")
        self.label_14 = QLabel(self.tab_2)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(380, 190, 75, 16))
        self.label_14.setStyleSheet(u"color: white;")
        self.enviar = QPushButton(self.tab_2)
        self.enviar.setObjectName(u"enviar")
        self.enviar.setGeometry(QRect(390, 260, 91, 24))
        self.enviar.setStyleSheet(u"background-color:teal; border-radius:0; color:white;")
        self.cedula = QLineEdit(self.tab_2)
        self.cedula.setObjectName(u"cedula")
        self.cedula.setGeometry(QRect(380, 150, 113, 24))
        self.contrasenia = QLineEdit(self.tab_2)
        self.contrasenia.setObjectName(u"contrasenia")
        self.contrasenia.setGeometry(QRect(380, 220, 113, 24))
        self.label_15 = QLabel(self.tab_2)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(50, 120, 291, 181))
        self.label_15.setPixmap(QPixmap(u"desk_app/assets/material-design-wallpaper-2.png"))
        self.label_15.setScaledContents(True)
        self.label_17 = QLabel(self.tab_2)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(0, 110, 581, 201))
        self.label_17.setPixmap(QPixmap(u"desk_app/assets/material-design-wallpaper-2.png"))
        self.label_17.setScaledContents(False)
        self.tabWidget.addTab(self.tab_2, "")
        self.label_17.raise_()
        self.label_4.raise_()
        self.label_6.raise_()
        self.label_8.raise_()
        self.label_10.raise_()
        self.label_12.raise_()
        self.label_14.raise_()
        self.enviar.raise_()
        self.cedula.raise_()
        self.contrasenia.raise_()
        self.label_15.raise_()
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(220, 40, 171, 31))
        font3 = QFont()
        font3.setFamily(u"Ubuntu Mono")
        font3.setPointSize(20)
        font3.setBold(True)
        font3.setWeight(75)
        self.label_2.setFont(font3)
        self.label_2.setStyleSheet(u"color: white;")
        self.label_2.setAlignment(Qt.AlignCenter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label.setText("")
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"RESULTADOS DE PRUEBA DE CO", None))
        self.label_7.setText("")
        self.label_3.setText("")
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Los resultados de su prueba de CO fueron: ", None))
        self.ppm.setText(QCoreApplication.translate("MainWindow", u"100", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Por tanto su moto:", None))
        self.resultado.setText(QCoreApplication.translate("MainWindow", u".........", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"ppm", None))
        self.label_16.setText("")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"Prueba", None))
        self.label_4.setText("")
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"FORMULARIO DE ENV\u00cdO", None))
        self.label_8.setText("")
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Porfavor rellene sus datos para guardarlos.", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"C\u00e9dula", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Placa", None))
        self.enviar.setText(QCoreApplication.translate("MainWindow", u"Enviar", None))
        self.label_15.setText("")
        self.label_17.setText("")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"Env\u00edo", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Prueba de CO", None))
    # retranslateUi

