# Generated by Django 4.0.6 on 2022-07-16 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motocicleta',
            name='propietario_cedula',
            field=models.ForeignKey(db_column='Propietario_cedula', on_delete=django.db.models.deletion.CASCADE, to='web_app.propietario'),
        ),
        migrations.AlterField(
            model_name='prueba',
            name='motocicleta_placa',
            field=models.ForeignKey(db_column='Motocicleta_placa', on_delete=django.db.models.deletion.CASCADE, to='web_app.motocicleta'),
        ),
        migrations.AlterField(
            model_name='prueba',
            name='oficina_idoficina',
            field=models.ForeignKey(db_column='Oficina_idOficina', on_delete=django.db.models.deletion.CASCADE, to='web_app.oficina'),
        ),
    ]
