# Generated by Django 4.0.6 on 2022-07-16 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_alter_motocicleta_propietario_cedula_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motocicleta',
            name='categoria',
        ),
    ]
