# Generated by Django 4.0.6 on 2022-07-18 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_remove_motocicleta_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='propietario',
            name='contra',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
