# Generated by Django 4.0.6 on 2022-07-19 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0004_propietario_contra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficina',
            name='d_ubicacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='oficina',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prueba',
            name='p_dioxido',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
