# Generated by Django 4.0.6 on 2022-07-19 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0005_alter_oficina_d_ubicacion_alter_oficina_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motocicleta',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='motocicleta',
            name='f_fabricacion',
        ),
    ]
