# Generated by Django 4.0.6 on 2022-07-19 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0006_remove_motocicleta_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prueba',
            name='f_prueba',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
