# Generated by Django 4.0.6 on 2022-07-19 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0007_alter_prueba_f_prueba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prueba',
            name='resultado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
